[package]
edition      = "2024"
name         = "rust-reterminal-e1002-examples"
rust-version = "1.88"
version      = "0.1.0"
license      = "MIT OR Apache-2.0"
description  = "Rust Embassy examples for the Seeed Studio reTerminal E1002 carrier board (XIAO ESP32-S3)"
keywords     = ["esp32s3", "embassy", "embedded", "reterminal", "seeed"]
categories   = ["embedded", "no-std"]

[dependencies]
esp-hal = { version = "~1.1.0", features = ["defmt", "esp32s3", "unstable"] }

esp-rtos = { version = "0.3.0", features = ["defmt", "embassy", "esp32s3"] }

defmt                  = "1.0.1"
esp-bootloader-esp-idf = { version = "0.5.0", features = ["defmt", "esp32s3"] }

embassy-executor = { version = "0.10.0", features = ["defmt"] }
embassy-time     = { version = "0.5.0", features = ["defmt"] }
esp-println      = { version = "0.17.0", features = ["defmt-espflash", "esp32s3"] }

critical-section = "1.2.0"
static_cell      = "2.1.1"
epdsi            = { git = "https://github.com/melastmohican/epdsi", features = ["defmt"] }

[dev-dependencies]
nb               = "1.1.0"
embedded-sdmmc   = "0.7.0"
embedded-hal-bus = "0.2.0"


# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2     # prefer slower builds but better debugging experience
lto           = 'fat'
opt-level     = 's'
